# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: alonewithnumbers
# Description of the Site
description: A repertoire
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Physics,Griffith's,griffiths,electrodynamics
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://cdn.discordapp.com/attachments/1219010514739527842/1219390161482158160/alonewithnumbers_angry_ncr_ranger_breathing_lots_of_green_gas_c_6c3b24d6-c6c6-45bd-992a-820d227e2976.png?ex=660b2095&is=65f8ab95&hm=b3cbaa8eee3d925e8a23ab2b3b195f298bb89d056800e3f32053f9404cf03736&
# If you don't want to use any icon, you can leave them blank.
email: alonewithnumbers@proton.me
#facebook_username: google.com
#twitter_username: google.com
#instagram_username: google.com
#linkedin_username: google.com
github_username:  alonewithnumbers
#youtube_channel_id: google.com
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
# google-analytics: UA-163806439-1

# Disqus
# disqus-shortname: thedevslot

# Name of the Author
author-name: alonewithnumbers
# URL for the Image of the Author
author-image: https://cdn.discordapp.com/attachments/1219010514739527842/1219387458857341061/alonewithnumbers_angry_ncr_ranger_breathing_lots_of_green_gas_c_8be50c34-27b0-4133-86ac-bb3c198d83ef.png?ex=660b1e11&is=65f8a911&hm=9b4830c06b30b4ce41ed1fa11326e21133587067bafc40ba5f9c795cbdab3456&
# 60 Words About the Author
author-about: Feel free to reach out if you have comments on any of my notes or projects by clicking the "CONTACT ME" button below.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/alonewithnumbers

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
